### ISSUE TITLE
Trojan:Win32/CryptInject!ml: instaloader-v4.6.1-windows-standalone.zip->instaloader.exe

### ISSUE THREAD

**Issue by somera** [instaloader/instaloader#1002]
**Describe the bug**

There is an Trojan in instaloader-v4.6.1.zip

**Comment by AplhaSlayer1964** [comment]
What anti virus gave you this message? I'm using kaspersky internet security and it found nothing after a scan.

**Comment by somera** [comment]
> What anti virus gave you this message? I'm using kaspersky internet security and it found nothing after a scan.

Windows Defender. The old ZIPs are ok.

**Comment by DReaper** [comment]
Can confirm, I get the same trojan warning with Windows Defender. Never had an issue with past versions.

**Comment by ThomasAn73** [comment]
Using pip install is fine, but windows.zip detects a trojan. Windows defender.
![Clipboard-2](https://user-images.githubusercontent.com/3271277/106393865-96322b00-63b6-11eb-940a-64e65f56ff90.jpg)

**Comment by aandergr** [comment]
Indeed, [VirusTotal for Instaloader 4.6.1 windows exe](https://www.virustotal.com/gui/file/43013ba22976cab77a601a09c59f5d8649ba3bb8c529e2882b79380dfc55c36d) shows that currently two antiviruses report the windows exe as malicious. It seems that this happens from time to time (already had #823 for version 4.5.3).

You could report this false-positive to your antivirus vendor, helping them to ship better software and sparing other users that scary message.

**Comment by aandergr** [comment]
This is fixed for Microsoft Defender Antivirus with one of the latest Security Intelligence Updates (I think version 1.331.422.0).

Thanks a lot to whoever reported this!

**Comment by somera** [comment]
Now I have ...

![image](https://user-images.githubusercontent.com/8334250/107145182-369cc800-6940-11eb-9d10-7a77ccb9de32.png)

And still other virus ;)

![image](https://user-images.githubusercontent.com/8334250/107145193-44524d80-6940-11eb-8204-c7b68461330d.png)

**Comment by DReaper** [comment]
I am still having this flagged as Trojan:Win32/Wacatac.D4!ml in Windows Security on Windows 10.  Virus definition is up to date on 1.331.1479.0

**Comment by aandergr** [comment]
What about version 4.6.2?

However, as I have said previously, there is probably nothing we can do about that. I suggest that you contact your antivirus software vendor.
