### ISSUE TITLE
Hashtag.from_name(): KeyError: 'graphql'

### ISSUE THREAD

**Issue by Exyss** [instaloader/instaloader#1080]
Found an error given by using wrong json metadata. 
Tried using different hashtags and to revert to previous versions of Instaloader, but it still gives the problem.
I also checked your built-in code and everything looks fine to me, so I suppose it has something to do with Instagram changing it's metadata format.
Maybe this was already fixed for other types of objects but you forgot to fix it for Hashtags (?)

```
Traceback (most recent call last):
  File "C:\Users\exyss\Desktop\v3.0-beta\src\test.py", line 6, in <module>
    hashtag = instaloader.Hashtag.from_name(_loader.context, "cats")
  File "C:\Users\exyss\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\structures.py", line 1302, in from_name
    hashtag._obtain_metadata()
  File "C:\Users\exyss\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\structures.py", line 1316, in _obtain_metadata        
    self._node = self._query({"__a": 1})
  File "C:\Users\exyss\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\structures.py", line 1311, in _query
    return self._context.get_json("explore/tags/{0}/".format(self.name),
KeyError: 'graphql'
```

**Comment by MarcoChilese** [comment]
I also have this error, an update would be nice

**Comment by santinmike** [comment]
I am using Instaloader 4.7.1. I have the same error. It seems to be a bug due to some recent changes made by Instagram.

**Comment by aandergr** [comment]
Thanks for reporting. Indeed, the structure of the data returned by Instagram for the query that is used there has changed recently.

Luckily though, the alternative described in https://github.com/instaloader/instaloader/issues/874#issuecomment-731561430 still works and can be used instead until this is fixed.

**Comment by martacosano** [comment]
Hello! 
Does the error depends on the account of instagram that I use to download the images?

I try to download images from a hashtag, when I use my personal account of instagram to do it I don’t have that problem. But when I use a new account that I created just for this I have the same problem.
Thank you,

**Comment by hobzcalvin** [comment]
Hi folks, any updates? I have an art project that is dead in the water without hashtag support. I can try digging into the code myself if someone provides guidance on what's happening.

**Comment by TomaszWychocki** [comment]
@hobzcalvin you can temporarily use my code. Just go through JSON and fetch all data you need (line 34). 

```
import instaloader
import settings
from datetime import datetime


def instaLogin():
    print("Logging in...")

    ses = instaloader.Instaloader()
    ses.context.sleep = False
    ses.login(settings.USER, settings.PASSWORD)

    print("...done")

    return ses


def fetchPostsData(session, hashtag):
    print("Fetching posts data...")

    jsonData = session.context.get_json(path="explore/tags/" + hashtag + "/", params={"__a": 1})
    hasNextPage = True
    pageNumber = 1

    while hasNextPage:
        print("Page " + str(pageNumber))
        sections = jsonData['data']['recent']['sections']

        for section in sections:
            for post in section['layout_content']['medias']:
                username = post['media']['user']['username']
                timestamp = datetime.fromtimestamp(post['media']['taken_at']).date()

                # ADD YOUR CODE HERE
                print(username, timestamp)

        hasNextPage = jsonData['data']['recent']['more_available']
        if hasNextPage:
            jsonData = session.context.get_json(
                path="explore/tags/" + hashtag + "/",
                params={"__a": 1,
                        "max_id": jsonData['data']['recent']['next_max_id']}
            )
        pageNumber += 1


def main():
    session = instaLogin()

    if session.context.is_logged_in:
        fetchPostsData(session, "github")
    else:
        raise Exception("Authentication failure!")


if __name__ == '__main__':
    main()
```

**Comment by francisbautista** [comment]
Here's a snippet that might elucidate #874 with datetime functionality taken from #121 . It takes posts between dates following a hashtag using the NodeIterator code and stores them in a list.

`
START = datetime(2021, 5, 28)
END = datetime(2021, 5, 30)
HASHTAG = "<Some Hashtag>"
GraphQL_Hash
posts = []

post_iterator = instaloader.NodeIterator(
    L.context, GraphQL_Hash,
    lambda d: d['data']['hashtag']['edge_hashtag_to_media'],
    lambda n: instaloader.Post(L.context, n),
    {'tag_name': HASHTAG},
    f"https://www.instagram.com/explore/tags/{HASHTAG}/"
)
        
def gen(start, end, posts):
    for post in posts:
        if post.date > start and post.date > end:
            pass
        elif post.date >= start and post.date <= end:
            yield post
        elif post.date <= start:
            break

for post in gen(start=START, end=END, posts=post_iterator):
    posts.append(post)

`
Hope this helps. Added a

**Comment by pwallace** [comment]
Same issue, always happens when logged in. Using version 4.7.1 installed via pip3.

Traceback effectively identical to the one shared by martacosano, above.

**Comment by pvita** [comment]
Same problem every time I try to log in

**Comment by jiggleexe** [comment]
@Showmaster3000 not fixed yet? It's working when not logged in but when logged in it's throwing graphql error please fix this one

**Comment by frankjuniorr** [comment]
Hello, folks.

Same problem with me using the version `4.7.2`.
When i try without login, it trigger a error:
```python
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
KeyError: 'edge_sidecar_to_children'

instaloader.exceptions.LoginRequiredException: Redirected to login page. Use --login.
```

If i try login with my personal account, it trigger a same error with this issue:
```python
KeyError: 'graphql'
```

**Comment by Leonardomorn** [comment]
Same error here, @frankjuniorr . I'm using the version `4.7.4`

**Comment by bwsyn** [comment]
Same issue as @frankjuniorr on version `4.7.4`

**Comment by JoseConi** [comment]
> Here's a snippet that might elucidate #874 with datetime functionality taken from #121 . It takes posts between dates following a hashtag using the NodeIterator code and stores them in a list.
> 
> ```
> START = datetime(2021, 5, 28)
> END = datetime(2021, 5, 30)
> HASHTAG = "<Some Hashtag>"
> GraphQL_Hash = "<Some GQL hash>"
> posts = []
> 
> post_iterator = instaloader.NodeIterator(
>     L.context, GraphQL_Hash,
>     lambda d: d['data']['hashtag']['edge_hashtag_to_media'],
>     lambda n: instaloader.Post(L.context, n),
>     {'tag_name': HASHTAG},
>     f"https://www.instagram.com/explore/tags/{HASHTAG}/"
> )
>         
> def gen(start, end, posts):
>     for post in posts:
>         if post.date > start and post.date > end:
>             pass
>         elif post.date >= start and post.date <= end:
>             yield post
>         elif post.date <= start:
>             break
> 
> for post in gen(start=START, end=END, posts=post_iterator):
>     posts.append(post)
> ```
> 
> Hope this helps. Edited for formatting.

What is a "GQL hash"?
I did it:
![er1](https://user-images.githubusercontent.com/79027875/125129892-7970f080-e0d6-11eb-83b9-7921410b0024.png)
And the output was this error:
![er2](https://user-images.githubusercontent.com/79027875/125129929-84c41c00-e0d6-11eb-9839-c9615083a555.png)
Where can i find the GQL hashtag for my "home" hashtag?

**Comment by fjenett** [comment]
I'm using this temp fix at the moment:

```python
from typing import Iterable
from instaloader import Hashtag, Post

def make_post (post_data):
  post = Post(L.context, post_data)
  post._node['taken_at_timestamp'] = post._node['taken_at']
  if 'image_versions2' in post._node:
    img_first = post._node['image_versions2']
  elif 'carousel_media' in post._node:
    img_first = post._node['carousel_media'][0]['image_versions2']
  if img_first:
    urls_sorted = sorted(img_first['candidates'], key=lambda u: u['width'] )
    post._node['display_url'] = urls_sorted[0]['url']
  post._node['is_video'] = 'video_duration' in post._node
  return post

def get_posts_from_sections ( sections ) -> Iterator[Post]:
  yield from ( make_post(media['media']) 
                for sec in sections
                  for media in sec['layout_content']['medias'] )


def get_hashtag_posts ( hashtag_name ) -> Iterator[Post]:
  page = 1
  response = L.context.get_json("explore/tags/{0}/".format(hashtag_name), {"__a": 1})
  data = response['data']

  # fetch top posts
  if 'top' in data:
    yield from get_posts_from_sections(data['top']['sections'])

  # fetch recent posts
  max_id = data['recent']['next_max_id']
  yield from get_posts_from_sections(data['recent']['sections'])

  while data['recent']['more_available']:
      response = L.context.get_json(
          "explore/tags/{0}/".format(hashtag_name), 
          {"__a": 1, "max_id": max_id})
      
      data = response['data']
      max_id = data['recent']['next_max_id']
      page += 1

      print('Page {:03} width ID {}'.format(page, max_id))

      # fetch top posts
      if 'top' in data:
        yield from get_posts_from_sections(data['top']['sections'])

      yield from get_posts_from_sections(data['recent']['sections'])


# start downloading

# Note that "L" is an instance of Instaloader with a logged in user using this method:
# https://github.com/instaloader/instaloader/issues/929

hashtags = [
  # put your hashtags here
]

for hashtag_name in hashtags:
  posts = get_hashtag_posts(hashtag_name)

  for post in posts:
    L.download_post(post, target="#"+hashtag_name)
```

**Comment by pvita** [comment]
Hashtag collection:

login: KeyError: 'graphql'
no login: Errors or warnings occurred:
Get hashtag #....: Redirected to login page. Use --login

Any solution?

**Comment by ahmetfurkanoruc** [comment]
As far as I understand, the Hashtag graphql structure of api and the graphql structure of Instagram cannot work in harmony. Did the developers of the api fix this problem? Or is there any other solution? I can't do any development related to hashtag.

**Comment by aandergr** [comment]
Thanks to you all for sharing your observations and for creating such a beautiful collection of workarounds for this issue!

The download of hashtags should now be fixed in Instaloader's latest pre-release, [Version 4.9b1](https://github.com/instaloader/instaloader/releases/tag/v4.9b1).

**Comment by chaim6888** [comment]
I've installed instaloader 4.9b1 but I still get the KeyError 'graphql' for the download of the hashtags

**Comment by xTaromarux** [comment]
I still get the KeyError 'graphql' for the download everything(I try download video from account), has anyone fixed this problem? ;-;

**Comment by bishalnepali** [comment]
Bug is still there.

**Comment by pvita** [comment]
I can confirm this error still appears when you try to collect geotags

**Comment by scanansi** [comment]
Hi all, i also use the alternate hashtag post fetch code, but i found recently that max_id isn't working to get subsequent pages. Is anyone else noticing that you cant get more than the initial page?

`if hasNextPage:
            jsonData = session.context.get_json(
                path="explore/tags/" + hashtag + "/",
                params={"__a": 1,
                        "max_id": jsonData['data']['recent']['next_max_id']}
            )`

I can't get the next page.

**Comment by tallevy22** [comment]
none of the above examples worked for me, 

> [evanmiltenburg](/evanmiltenburg)

[evanmiltenburg](https://github.com/evanmiltenburg) example returned only a single post, but I know that there are 147 posts I retrieved through the command line, can anyone please advise on this?
