### ISSUE TITLE
Instaloader.get_location_posts(): TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by queensoft666** [instaloader/instaloader#1129]
**Describe the bug**
ERROR: Failed to execute script __main__

**To Reproduce**
Command line:
`instaloader.exe %1035567819 --login XXXXXXXXXXX -p XXXXXXXXXXX --no-compress-json --no-video-thumbnails`
Account is OK, tested in browser.

**Expected behavior**
Download images for that specific location:
https://www.instagram.com/explore/locations/1035567819/talpa-bascoveni-teleorman/

**Error messages and tracebacks**
```
Loaded session from C:\Users\Queen Soft\AppData\Local\Instaloader\session-XXXXXXXXXXXXXXXXX.
Logged in as XXXXXXXXXXXXXXXXXXX.
Retrieving pictures for location 1035567819...
Traceback (most recent call last):
  File "__main__.py", line 478, in <module>
  File "__main__.py", line 475, in __main
  File "__main__.py", line 445, in main
  File "__main__.py", line 163, in _main
  File "instaloader\instaloader.py", line 64, in call
  File "instaloader\instaloader.py", line 1044, in download_location
  File "instaloader\instaloader.py", line 894, in posts_download_loop
  File "instaloader\instaloader.py", line 1014, in get_location_posts
TypeError: 'NoneType' object is not subscriptable
[8584] Failed to execute script __main__
```

**Instaloader version**
4.7.1

**Additional context**
Windows 10 x64 2004 19041.928
I have full admin rights.

Older version of instaloader (4.6.2) worked a few days ago.
Older version (4.6.2) is also not working right now.

Delete session file - login is OK - but same error afterwards.
Session file is NOT created, but login says OK every time I run the command.
```
Session file does not exist yet - Logging in.
Logged in as XXXXXXXXXXXXXX.
```

Thank you.

**Comment by aandergr** [comment]
Indeed, this does not seem to work anymore. Thanks for this exemplary bug report!



> Session file is NOT created, but login says OK every time I run the command.

Session file is created at the end of Instaloader's execution (unless it terminates due to an error). However, you can use `instaloader --login LOGIN [--password PASSWORD] [--sessionfile SESSIONFILE]` (without any further arguments) to only login and create a sessionfile.

**Comment by queensoft666** [comment]
Yes, I noticed session file is created at the end of the run (profile and other types of download are working fine).

**Comment by queensoft666** [comment]
Download #hashtag also not working, same(?) error.
```
instaloader.exe "#tatarasti" --login XXXXXXXXXXXXX -p XXXXXXXXXXX -C --no-video-thumbnails
Loaded session from C:\Users\Queen Soft\AppData\Local\Instaloader\session-XXXXXXXXXXXXXXXXXXXX.
Logged in as XXXXXXXXXXXXXXXXX.
Traceback (most recent call last):
  File "__main__.py", line 478, in <module>
  File "__main__.py", line 475, in __main
  File "__main__.py", line 445, in main
  File "__main__.py", line 157, in _main
  File "instaloader\instaloader.py", line 1095, in download_hashtag
  File "instaloader\structures.py", line 1323, in from_name
  File "instaloader\structures.py", line 1337, in _obtain_metadata
  File "instaloader\structures.py", line 1332, in _query
KeyError: 'graphql'
[7100] Failed to execute script __main__
```

**Comment by queensoft666** [comment]
Updated to 4.7.2, same error:
```
Retrieving pictures for location 114304211920174...
Traceback (most recent call last):
  File "__main__.py", line 478, in <module>
  File "__main__.py", line 475, in __main
  File "__main__.py", line 445, in main
  File "__main__.py", line 163, in _main
  File "instaloader\instaloader.py", line 64, in call
  File "instaloader\instaloader.py", line 1044, in download_location
  File "instaloader\instaloader.py", line 894, in posts_download_loop
  File "instaloader\instaloader.py", line 1014, in get_location_posts
TypeError: 'NoneType' object is not subscriptable
[17520] Failed to execute script __main__
```

**Comment by queensoft666** [comment]
Updated to 4.7.3, same errors.

**Comment by danielgabas** [comment]
same issue

**Comment by queensoft666** [comment]
Don't want to be rude  / out of line, but is anyone working on this issue ?!

**Comment by queensoft666** [comment]
Version 4.8 still not working.

**Comment by aandergr** [comment]
`Instaloader.get_location_posts()` should now be fixed in Instaloader's latest pre-release, [Version 4.9b1](https://github.com/instaloader/instaloader/releases/tag/v4.9b1).

**Comment by queensoft666** [comment]
Problem is still present for me.
The only difference is the loop is happening after 71 posts, not 63 like before.
I can send video recording, if it helps

Also, regular release 4.8.5 still has location download error.
```
TypeError: 'NoneType' object is not subscriptable
[20956] Failed to execute script __main__
```
