### ISSUE TITLE
Big bug with hashtag search

### ISSUE THREAD

**Issue by Kal-Toh** [instaloader/instaloader#1593]
When searching for a hashtag the program breaks completely giving a huge amount of errors (too much to copy over). I'm assuming this is after an update from IG as I haven't changed anything on my utilization of the code and tried it fresh. 

This can be reproduced by using this minimal code:
from instaloader import Hashtag, Instaloader
htag = "python.hub"
l = Instaloader()

print(htag)
h = Hashtag.from_name(l.context, htag)
print(h.mediacount)

Instead of printing the post count, it will fail to run resulting in hundreds of lines of errors.
I am using the latest version of instaloader.

If someone could try the above code to verify that this issue is not on my end alone that would be appreciated.

**Comment by sajaddadgar** [comment]
I get the same error. 
Instaloader.Hashtag.from_name doesn't work.

**Comment by Kal-Toh** [comment]
Thanks for the confirmation, the issue seems to be with the entire hashtag module. The same error occurs when using the hashtag function in Instaloader via terminal.

**Comment by Showmaster3000** [comment]
Looks like duplicate of #1588 and #1589.

**Comment by zq99299** [comment]
I have the same problem

```
# v4.9.1
import instaloader  

L = instaloader.Instaloader()

hashtag = instaloader.Hashtag.from_name(L.context, "dress")
```

Error reported directly
![image](https://user-images.githubusercontent.com/11927113/174518842-256b76e1-3fb4-4bd4-a66a-d620a37e1348.png)

**Comment by pardan** [comment]
any update?

**Comment by Kal-Toh** [comment]
> Looks like duplicate of #1588 and #1589.

Those issues look like they deal with the downloading of posts not the metrics, the error received also appears different if you try running the example code I included in the OP or look at zq99299's post. 

That being said, I'm sure the cause of both these issues are related.

**Comment by Kal-Toh** [comment]
**UPDATE:**
This issue seems to have been resolved. Can others who have been experiencing this please confirm it has been removed for them also?

I can't seem to see any update so I'm curious as to what might have caused the bug.

**Comment by JoeGarcia2** [comment]
I'm still getting the bug. My situation is the same as #1588. Not logged in downloads photos by hashtag. Logged in gives the JSON Query error. It seems like Instagram is sending a different format, as my own personal scraping tool shows HTML and not the expected JSON.

**Comment by Kal-Toh** [comment]
> I'm still getting the bug. My situation is the same as #1588. Not logged in downloads photos by hashtag. Logged in gives the JSON Query error. It seems like Instagram is sending a different format, as my own personal scraping tool shows HTML and not the expected JSON.

As that's not what this issue is about I'm closing it.
