### ISSUE TITLE
 Wrong directory output for tagged and highlights

### ISSUE THREAD

**Issue by UnbelievableCat** [instaloader/instaloader#304]
**Describe the bug**
Instaloader creates tagged and higlights folders in same directory as profile folder. Example:
\profile_name
\profile_name ﹨꞉tagged
\profile_name﹨highlight

**To Reproduce**
instaloader -l user -p pass profile_name --tagged --higlights 

**Expected behavior**
Create folder in profile directory

**Instaloader version**
Windows standalone 4.2.7.

**Comment by psylenced** [comment]
Similar problem for me (Windows).

The backslash is some how being replaced with a unicode backslash.

**Comment by pxssy** [comment]
An issue related to this, for older versions, was that some highlights had slashes in their names, which caused certain errors when trying to save. instaloader would give up instantly, leaving the rest of the highlights without issues unable to be downloaded.

**Comment by psylenced** [comment]
Any update on this?

Tagged/highlights are useless at the moment.

**Comment by psylenced** [comment]
I think i've tracked it down to this commit:

https://github.com/instaloader/instaloader/commit/0c9a667da74d5dd27664d307130223edf530f4d9

The purpose of that commit (I assume) is to replace back-slashes in story titles with a unicode variation.

The problem is when you have a multi-path save ```profile\tagged``` or ```profile\highlights``` it seems to replace the windows path separator too.

What's happening:

```ReplaceWithUnicode(profilename\tagged) + \ + ReplaceWithUnicode(Filename)```

What it should do:

```ReplaceWithUnicode(profilename) + \ + tagged + \ + ReplaceWithUnicode(Filename)```

**Comment by psylenced** [comment]
Following on:

https://github.com/instaloader/instaloader/blob/b542936c0927015316a2b3800b6de8c13f9b7426/instaloader/instaloader.py#L456

```
        dirname = _PostPathFormatter(post).format(self.dirname_pattern, target=target)
        filename = dirname + '/' + self.format_filename(post, target=target)
```

The inputs for that are:

```
pattern = {target}
target = profilename\:tagged
```

The output is
```dirname = profilename﹨꞉tagged``` (note the unicode backslash)

So the finale filename is:

```
profilename﹨꞉tagged/anotherprofile_2016-01-11_12-12-12_12345-123456789123456789
```

with ```"profilename﹨꞉tagged"``` being a single first-level folder.

Meaning in the download root folder you have:

```
profile1
profile1﹨꞉tagged
profile1﹨:highlights
profile2
profile2﹨꞉tagged
profile2﹨꞉highlights
profile3
profile3﹨꞉tagged
profile3﹨꞉highlights
```

This only happens on windows due to the unicode replacement linked above.

This bug is causing any sub-level folders to be broken in windows (:highlights / :tags / :stories).

**Comment by psylenced** [comment]
This is still an outstanding issue for windows installations.

**Comment by i-cant-git** [comment]
I have the same issue on Windows.

```
$ instaloader --version
4.2.10

$ python --version
Python 3.7.3
```

**Comment by psylenced** [comment]
@Thammus are you able to have a look at the change you made?

**Comment by pxssy** [comment]
Is it possible to manually edit the faulty code? this seems to be just 1 weird character.

**Comment by psylenced** [comment]
Could potentially just reverse the change made in:

0c9a667da74d5dd27664d307130223edf530f4d9

Not sure what it was originally trying to fix though.

**Comment by DankMemeGuy** [comment]
Is there anything happening with this? any workaround?

**Comment by DankMemeGuy** [comment]
Not sure how to merge the changes. But my copy fixes the issue.

https://github.com/DankMemeGuy/instaloader/commit/f32fcea30e6b5983bdae4543784e53ced2900f9d

**Comment by aandergr** [comment]
Thanks for reporting! This bug has been fixed with [Version 4.4.3](https://github.com/instaloader/instaloader/releases/tag/v4.4.3).

**Comment by b80d2b** [comment]
I have found out that when the highlights name is "..." it is trying to create a directory with the path like "{profile}/.../" and then crashes, because it is actually the grandparent address. Is there a possibility to change dir_patter for specific target? I now fixed it by making highlight return quoteted title "'...'" in this case

**Comment by HeiwaRyuu** [comment]
Still not fixed for the python package -> "pip install instaloader".
