### ISSUE TITLE
Username does not exist error on public profiles.

### ISSUE THREAD

**Issue by DMScoder** [instaloader/instaloader#778]
**Describe the bug**
When running `instaloader.Profile.from_username()` with a logged in context and a username that exists, an error is returned saying the profile doesn't exist, and recommending that same exact profile. I have double checked to make sure the usernames are correct and that there isn't any hidden formatting. 

**To Reproduce**
Using the `instaloader.Profile.from_username(loader.context, username)` on a few dozen accounts, some should error out saying they don't exist, but showing the most similar account as exactly the same name. This occurs specifically when logged in.

When I then try this same username from the command line using `instaloader username` it works fine 

**Expected behavior**
When getting the profile using the from_username() function, it should always return a user if that user's profile exists and is public.

**Error messages and tracebacks**
`[ERROR] with instaloader username uniliga_gg: Profile uniliga_gg does not exist.
The most similar profile is: uniliga_gg.`

**Instaloader version**
4.4.5

**Additional context**
The profiles that don't work seem to work fine from the commandline.

**Comment by threnbo** [comment]
Same here. Same error on public and private accounts (that I am a comfirmed follower of). I created a new 'test' account and tried to scrape the same public accounts - no errors. I changed the username/name/birthday of my 'real' account and checked again, nothing changed, still the same error. I am glad if I could provide more information to solve the problem. Thanks!

**Comment by DMScoder** [comment]
> The most likely explanation for the described behavior is that the profile in question has blocked the account you are using. Is it possible to view the profile with the Instagram App using the same account?
> 
> > When I then try this same username from the command line using `instaloader username` it works fine
> 
> Using the CLI, Instaloader accesses a blocked profile anonymously.
> 
> `instaloader.Profile.from_username(loader.context, 'uniliga_gg')` works fine for me.

So I cycle several accounts for scraping but have not had trouble accessing the non-existing users from the app. The non-existing accounts have no relation to the accounts I am logging in with, so if there is a block in place it is by instagram itself. Is it possible for accounts to be blocked on a region basis?

Looking at @Drod917's edits, my current workaround is to check if a recommended username is the same as the one in question, and scrape it anonymously if it is.

**Comment by mbande** [comment]
exactly the same problem, i'm nearly sure that my accounts is not blocked by target profiles. so there should be something else related to account or target profile

**Comment by mbande** [comment]
i logged in with my account and viewed the target profile with no problem. but instaloader throws ProfileNotExistsException with exact same target username suggestion! the problem may be something related to session, as it works with one and fails for another

**Comment by naohide** [comment]
I'm facing the same issue.
Now, I found the problem on https://github.com/instaloader/instaloader/blob/master/instaloader/instaloadercontext.py#L354-L355.
I changed regex and work fine.
```
match = re.search(r'window\.__additionalDataLoaded\([^{]+.*"graphql":({.*}).*}\);<\/script>', resp.text)
```

**Comment by Thammus** [comment]
This is fixed with [Instaloader 4.5.3](/instaloader/instaloader/releases/tag/v4.5.3).

**Comment by vviola-huuno** [comment]
It's not fixed for me and I can confirm that it happens with accounts that require age verification and therefore to be logged.

**Comment by isaac1902** [comment]
It's not fixed for me and I can confirm that it happens with accounts that require age verification and therefore to be logged.
